SIBCProject/SIBCProject/Controllers/UserRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SIBCProject.Models;

namespace SIBCProject.Controllers
{
    public class UserRegistrationController : Controller
    {
        
        // GET: /UserRegistration/
        //static List<UserRegistration> user = new List<UserRegistration>();
        
        public ActionResult WorkwithUs()
        {
           UserRegistration user = new UserRegistration();
            return View(user);
        }

        [HttpPost]
        public ActionResult WorkwithUs(UserRegistration us)
        {
        
             Savexml.SaveData(us);
             return Content("Record Added");
        }
    }
}

SIBCProject/SIBCProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/floral/style.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.5.3.js")" type="text/javascript"></script>
    <script src="@Url.Content("http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.5.1.min.js")" type="text/javascript"></script>
</head>
<body>
    <div id="container">
  <div id="banner">
      <img id="img_logo" alt="Logo" src="http://www.sibc-tukwila.org/img/logo.png") />
  </div>
   <div id="navcontainer">  
       <ul id="navlist">
           <li>@Html.ActionLink("Home", "Index", "Home")</li>
           <li>@Html.ActionLink("Calendar", "Calendar", "Calendar")</li>
           <li>@Html.ActionLink("Get Involved", "GetInvolved", "Home")</li>
           <li>@Html.ActionLink("Visit", "Visit", "Home")</li>
           <li>@Html.ActionLink("Work with Us", "WorkwithUs", "UserRegistration")</li>
           <li>@Html.ActionLink("Resources", "Resources", "Home")</li>
           <li>@Html.ActionLink("Gallery", "Gallery", "Home")</li>
           <li>@Html.ActionLink("Food Items", "FoodItems", "Home")</li>
       </ul>
        </div>
        <section id="main">
            @RenderBody()
        </section>
      @RenderSection("Scripts", false)  
    <style type="text/css"> 
    @RenderSection("Styles", false) 
</style>
        </div>
    <footer>
        Copyright 2016
    </footer>
</body>
</html>

SIBCProject/SIBCProject/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}